# Logistic Regression

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('score.csv')


In [3]:
df

Math Score  English score  admission
0           75             82          1
1           69             23          0
2            6             26          0
3           34             85          0
4           43             68          0
5           83             49          1
6           22             55          0
7            9             69          0
8           91             94          1
9           87             58          1
10          92             84          1
11          67             60          0
12          51             95          0
13          53             68          0
14          68             76          1
15          64             28          0
16          75             63          1
17          72             18          0
18          78             89          1

In [24]:
df[:10]['admission']

0    1
1    0
2    0
3    0
4    0
5    1
6    0
7    0
8    1
9    1
Name: admission, dtype: int64

In [5]:
#Manually split the data
X_train = df[:10].drop(['admission'], axis=1)
y_train = df[:10]['admission']
X_test = df[10:].drop(['admission'], axis=1)
y_test = df[10:]['admission']

In [25]:
X_train 

Math Score  English score
0          75             82
1          69             23
2           6             26
3          34             85
4          43             68
5          83             49
6          22             55
7           9             69
8          91             94
9          87             58

In [10]:
y_train

0    1
1    0
2    0
3    0
4    0
5    1
6    0
7    0
8    1
9    1
Name: admission, dtype: int64

In [29]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
lr.coef_

array([[0.33582749, 0.16435877]])

In [14]:
lr.intercept_

array([-31.57677082])

In [15]:
lr.predict(X_train)

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1])

In [31]:
lr.predict_proba(X_train)

array([[8.34610615e-04, 9.99165389e-01],
       [9.90285968e-01, 9.71403237e-03],
       [1.00000000e+00, 1.04076733e-11],
       [9.97950567e-01, 2.04943333e-03],
       [9.97426193e-01, 2.57380664e-03],
       [1.27361781e-02, 9.87263822e-01],
       [9.99999736e-01, 2.63599809e-07],
       [9.99999967e-01, 3.34381607e-08],
       [5.39158654e-07, 9.99999461e-01],
       [7.66407682e-04, 9.99233592e-01]])

In [32]:
#Calculate Accuracy
            
from sklearn.metrics import accuracy_score


In [33]:
y_pred_train = lr.predict(X_train)
print('Train Accuracy: %.2f' % accuracy_score(y_train, y_pred_train))
y_pred_test = lr.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(y_test, y_pred_test))

Train Accuracy: 1.00
Test Accuracy: 0.78


In [34]:
y_test , y_pred_test

(10    1
 11    0
 12    0
 13    0
 14    1
 15    0
 16    1
 17    0
 18    1
 Name: admission, dtype: int64, array([1, 1, 1, 0, 1, 0, 1, 0, 1]))

In [11]:
#Breast Cancer dataset

In [36]:
X.shape

(569, 30)

In [35]:
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()

X = breast_cancer.data # 
y = breast_cancer.target #  

print('Class labels:', np.unique(y))

print('Features names:', breast_cancer.feature_names)

print('# of dataset :', len(X))

Class labels: [0 1]
Features names: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
# of dataset : 569


In [44]:
#Train Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y)

In [16]:
lr = LogisticRegression( max_iter=100)
lr.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
y_pred_train = lr.predict(X_train)
print('Train Accuracy: %.2f' % accuracy_score(y_train, y_pred_train))
y_pred_test = lr.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(y_test, y_pred_test))

Train Accuracy: 0.94
Test Accuracy: 0.94


In [61]:
lr.coef_

array([[ 6.65039638e-02,  4.38674097e-03,  2.02650291e-01,
         5.42068320e-03, -2.82725631e-04, -5.55164641e-03,
        -8.50655909e-03, -3.21062002e-03, -8.80912339e-04,
         1.04612256e-04,  8.90544652e-04,  6.95476242e-04,
        -2.01781947e-02, -3.15415234e-02, -4.77062143e-05,
        -1.57865419e-03, -2.02675834e-03, -4.79803285e-04,
        -2.66733931e-04, -1.21165528e-04,  7.34866670e-02,
        -8.72435136e-02,  3.84229565e-03, -2.61629048e-02,
        -1.07305255e-03, -2.01883414e-02, -2.59232638e-02,
        -6.68675864e-03, -3.77527503e-03, -1.29561978e-03]])

In [62]:
lr.intercept_

array([0.01099027])

In [63]:
#Bank dataset

In [38]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/bank.csv')

df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [39]:
# Set X and y 
X = df.drop(['y'], axis=1)
#one hot encoding
X = pd.get_dummies(X)
y = df['y']

In [40]:
X

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0      30     1787   19        79         1     -1         0           0   
1      33     4789   11       220         1    339         4           0   
2      35     1350   16       185         1    330         1           0   
3      30     1476    3       199         4     -1         0           0   
4      59        0    5       226         1     -1         0           0   
...   ...      ...  ...       ...       ...    ...       ...         ...   
4516   33     -333   30       329         5     -1         0           0   
4517   57    -3313    9       153         1     -1         0           0   
4518   57      295   19       151        11     -1         0           0   
4519   28     1137    6       129         4    211         3           0   
4520   44     1136    3       345         2    249         7           0   

      job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  month_may  \
0                   0                 0  ...          0          0          0   
1                   0                 0  ...          0          0          1   
2                   0                 0  ...          0          0          0   
3                   0                 0  ...          1          0          0   
4                   1                 0  ...          0          0          1   
...               ...               ...  ...        ...        ...        ...   
4516                0                 0  ...          0          0          0   
4517                0                 0  ...          0          0          1   
4518                0                 0  ...          0          0          0   
4519                1                 0  ...          0          0          0   
4520                0                 1  ...          0          0          0   

      month_nov  month_oct  month_sep  poutcome_failure  poutcome_other  \
0             0          1          0                 0               0   
1             0          0          0                 1               0   
2             0          0          0                 1               0   
3             0          0          0                 0               0   
4             0          0          0                 0               0   
...         ...        ...        ...               ...             ...   
4516          0          0          0                 0               0   
4517          0          0          0                 0               0   
4518          0          0          0                 0               0   
4519          0          0          0                 0               1   
4520          0          0          0                 0               1   

      poutcome_success  poutcome_unknown  
0                    0                 1  
1                    0                 0  
2                    0                 0  
3                    0                 1  
4                    0                 1  
...                ...               ...  
4516                 0                 1  
4517                 0                 1  
4518                 0                 1  
4519                 0                 0  
4520                 0                 0  

[4521 rows x 51 columns]

In [41]:
#see features
X.columns

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown'],
      dtype='object')

In [42]:
print('# of dataset :', len(X))

# of dataset : 4521


In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1, stratify=y)

In [46]:
lr = LogisticRegression(C=0.1, max_iter=150)
lr.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=150,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
y_pred_train = lr.predict(X_train)
print('Train Accuracy: %.2f' % accuracy_score(y_train, y_pred_train))
y_pred_test = lr.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(y_test, y_pred_test))

Train Accuracy: 0.89
Test Accuracy: 0.90


In [48]:
lr.coef_

array([[-1.91635262e-02,  1.86918518e-05, -1.72590586e-02,
         3.99905410e-03, -1.43201454e-01,  1.71838792e-03,
        -6.84511831e-02, -9.68286383e-03, -3.33323222e-01,
        -4.13055210e-02, -1.61430601e-02,  1.86837433e-02,
         2.06971724e-01, -3.77152195e-02, -1.01853900e-01,
         5.85367831e-03, -5.75848856e-02, -2.78175387e-02,
         1.58026274e-02,  6.86171863e-02, -1.95735959e-01,
        -2.50995665e-01, -3.32489781e-02, -3.55207417e-01,
         2.45811263e-02, -1.42391688e-02, -3.75806644e-01,
        -2.30779314e-03,  2.95405066e-01, -6.73519503e-01,
        -1.06410188e-01, -2.71704249e-01,  8.99187568e-02,
         8.67790196e-02, -5.54812214e-01,  4.05951094e-02,
         8.64260387e-02,  1.34724211e-02,  1.86685783e-02,
         6.66720613e-03, -1.18776368e-01, -7.78389056e-02,
         9.68832901e-02, -5.56924403e-01, -7.90264465e-02,
         1.29027200e-01,  6.27118425e-02, -1.42912726e-01,
        -6.06836039e-03,  3.09746549e-01, -5.38879900e-0

In [49]:
lr.intercept_

array([-0.38292833])